cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/chuan/vPRKS/.waf-1.6.7-0a94702c61504c487a251b8d0a04ca9a/waflib/Tools/c_config.py", line 435, in run_c_code\n    bld.compile()\n  File "/home/chuan/vPRKS/.waf-1.6.7-0a94702c61504c487a251b8d0a04ca9a/waflib/Build.py", line 193, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task failed (exit status 1): \n\t{task 34142160: cxxprogram test.cpp.1.o -> testprog}\n[\'/usr/bin/g++\', \'test.cpp.1.o\', \'-o\', \'/home/chuan/vPRKS/build/.conf_check_9a1d0551212c9d703363e62dfbc51c79/testbuild/testprog\', \'-Wl,-Bstatic\', \'-Wl,-Bdynamic\', \'-L/usr/lib\', \'-lpython2.7\', \'-Wl,-Bsymbolic-functions\', \'-Wl,-z,relro\']\n'
